# Generated by Django 3.2.16 on 2022-12-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20221217_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "High"), (3, "Urgent")], default=2
            ),
        ),
    ]
