# Generated by Django 3.2.16 on 2023-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
