# Generated by Django 3.2.16 on 2023-01-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_task_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="image",
            new_name="picture_url",
        ),
    ]
