# Generated by Django 3.2.16 on 2023-01-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_rename_image_employee_picture_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="picture_url",
            new_name="image",
        ),
    ]
