# Generated by Django 3.2.16 on 2023-01-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_picture_url_employee_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('username',), 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority',)},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ('name',)},
        ),
    ]
